export interface LibrariesData {
  order: number;
  fullname: string;
  // kopuk: "010125";
  territory: string;
  address: string;
  formname: string;
  // period: "2013";
  libraries: number;
  buildings_repair: number;
  buildings_disrepair: number;
  buildings_management: number;
  libraries_computers: number;
  internet: number;
  // site: 63;
  "number_of_personal_computers_in_libraries,_units": number;
  computers: number;
  digital_catalogs: number;
  internet_catalogs: number;
  // electronic_catalogue_volume: 1822.6;
  // internet_catalogue_volume: 1770.3;
  // users: 733.5;
  // users_children: 198.2;
  // visits: 6695.5;
  // received_copies: 420.5;
  // received_electronic: 6.31;
  // out_of_instances: 449.42;
  // dropped_copies: 2.1;
  // copies: 10460.7;
  // copies_electronic: 44.4;
  // copies_issued: 17062;
  // issued_electronic: 1247.6;
  // copies_issued_children: 5355;
  // subscribers: 11924;
  // "individual_subscribers_(information_services),_units": 8560;
  // visits_sites: 547.1;
  // employees: 2177;
  // employees_staff: 1717;
  // staff_higheeducated: 997;
  // "staff_vocational,_people": 675;
  // funds: 523558;
  // funds_budget: 516401;
  // funds_entrepreneurial: 6965;
  // "funds_main_activity,_thousand_rubles": 3750;
  // funds_used: 522387;
  // "funds_staff,_thousand_rubles": 281760;
  // funds_acquisition: 32522;
}
